pragma ComponentBehavior: Bound

import Quickshell
import Quickshell.Io
import QtQuick

Scope {
    id: root

    property bool caffeineActive: false

    // Debounce timer — regenerate config 500ms after last change
    Timer {
        id: debounce
        interval: 500
        onTriggered: root._regenerate()
    }

    // Watch all idle Config properties
    Connections {
        target: Config
        function onIdleDimEnabledChanged() { debounce.restart() }
        function onIdleDimTimeoutChanged() { debounce.restart() }
        function onIdleLockEnabledChanged() { debounce.restart() }
        function onIdleLockTimeoutChanged() { debounce.restart() }
        function onIdleDpmsEnabledChanged() { debounce.restart() }
        function onIdleDpmsTimeoutChanged() { debounce.restart() }
        function onIdleSuspendEnabledChanged() { debounce.restart() }
        function onIdleSuspendTimeoutChanged() { debounce.restart() }
        function onIdleHibernateEnabledChanged() { debounce.restart() }
        function onIdleHibernateDelayChanged() { debounce.restart() }
    }

    // Generate on startup
    Timer {
        interval: 1000
        running: true
        onTriggered: root._regenerate()
    }

    function _buildConfig() {
        let lines = [];
        lines.push("# Auto-generated by Quickshell IdleManager — do not edit manually");
        lines.push("");
        lines.push("general {");
        lines.push("    lock_cmd = loginctl lock-session");
        lines.push("    before_sleep_cmd = loginctl lock-session");
        lines.push("    after_sleep_cmd = hyprctl dispatch dpms on");
        lines.push("}");

        if (Config.idleDimEnabled) {
            lines.push("");
            lines.push("listener {");
            lines.push("    timeout = " + Config.idleDimTimeout);
            lines.push("    on-timeout = brightnessctl -s set 10");
            lines.push("    on-resume = brightnessctl -r");
            lines.push("}");
        }

        if (Config.idleLockEnabled) {
            lines.push("");
            lines.push("listener {");
            lines.push("    timeout = " + Config.idleLockTimeout);
            lines.push("    on-timeout = loginctl lock-session");
            lines.push("}");
        }

        if (Config.idleDpmsEnabled) {
            lines.push("");
            lines.push("listener {");
            lines.push("    timeout = " + Config.idleDpmsTimeout);
            lines.push("    on-timeout = hyprctl dispatch dpms off");
            lines.push("    on-resume = hyprctl dispatch dpms on");
            lines.push("}");
        }

        if (Config.idleSuspendEnabled) {
            let cmd = Config.idleHibernateEnabled
                ? "systemctl suspend-then-hibernate"
                : "systemctl suspend";
            lines.push("");
            lines.push("listener {");
            lines.push("    timeout = " + Config.idleSuspendTimeout);
            lines.push("    on-timeout = " + cmd);
            lines.push("}");
        }

        lines.push("");
        return lines.join("\n");
    }

    function _regenerate() {
        let conf = _buildConfig();
        writeProc.command = ["bash", "-c",
            "cat > " + _confPath + " << 'IDLEEOF'\n" + conf + "IDLEEOF"];
        writeProc.running = true;
    }

    property string _homeDir: Quickshell.env("HOME")
    property string _confPath: _homeDir + "/jimdots/hypr/hypridle.conf"

    Process {
        id: writeProc
        command: ["true"]
        onExited: {
            if (!root.caffeineActive) {
                restartProc.running = true;
            }
        }
    }

    Process {
        id: restartProc
        command: ["bash", "-c", "pkill -x hypridle 2>/dev/null; while pgrep -x hypridle >/dev/null; do sleep 0.1; done; hypridle &"]
    }
}
