# uosc menu bindings
menu        script-binding uosc/menu
mbtn_right  script-binding uosc/menu

# uosc panels
tab         script-binding uosc/toggle-ui
o           script-binding uosc/open-file
P           script-binding uosc/items          # playlist
S           script-binding uosc/subtitles
A           script-binding uosc/audio
C           script-binding uosc/chapters
del         script-binding uosc/delete-file-quit

# playback
SPACE       cycle pause
RIGHT       seek  5
LEFT        seek -5
UP          seek  60
DOWN        seek -60
[           add speed -0.25
]           add speed  0.25
BS          set speed 1.0
9           add volume -5
0           add volume  5
m           cycle mute
f           cycle fullscreen
s           screenshot

# sponsorblock category toggle handled by sponsorblock_minimal automatically
