#!/usr/bin/env python3
"""Generate the combined keybinding cheatsheet from docs/keybindings.json.

Outputs:
  docs/KEYBINDINGS.md        — grouped human reference (read in editor/pager)
  quickshell/keybindings.json — co-located copy consumed by the quickshell
                                launcher's `k` keybindings provider (deployed
                                to ~/.config/quickshell/ via the dir symlink;
                                must sit next to AppLauncher.qml so the
                                Qt.resolvedUrl relative path works).

Run after editing the JSON:  ./scripts/gen-keybindings.py
"""
from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DATA = REPO / "docs" / "keybindings.json"
MD_OUT = REPO / "docs" / "KEYBINDINGS.md"
QS_OUT = REPO / "quickshell" / "keybindings.json"


def main() -> None:
    data = json.loads(DATA.read_text())
    sections = data["sections"]

    md: list[str] = [
        "# Keybindings",
        "",
        "Combined cheatsheet for Hyprland, Quickshell, zsh, tmux and Neovim.",
        "",
        "> Generated by `scripts/gen-keybindings.py` from `docs/keybindings.json` — "
        "edit the JSON, not this file. Press **Super+/** for the searchable popup.",
        "",
        "## Contents",
        "",
    ]
    for s in sections:
        anchor = s["label"].lower().replace(" ", "-")
        for ch in "—/(),.":
            anchor = anchor.replace(ch, "")
        anchor = "-".join(filter(None, anchor.split("-")))
        md.append(f"- [{s['label']}](#{anchor})")
    md.append("")

    for s in sections:
        md.append(f"## {s['label']}")
        md.append("")
        if s.get("note"):
            md.append(f"_{s['note']}_")
            md.append("")
        for group, binds in s["groups"].items():
            md.append(f"### {group}")
            md.append("")
            md.append("| Keys | Action |")
            md.append("| --- | --- |")
            for keys, desc in binds:
                md.append(f"| `{keys}` | {desc} |")
            md.append("")

    MD_OUT.write_text("\n".join(md).rstrip() + "\n")

    # Co-located copy for the quickshell launcher's `k` provider. Same schema
    # (sections[].groups), pretty-printed so it diffs cleanly in git.
    QS_OUT.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")

    n = sum(len(g) for s in sections for g in s["groups"].values())
    print(f"wrote {MD_OUT.relative_to(REPO)} ({n} bindings)")
    print(f"wrote {QS_OUT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
