#!/usr/bin/env python3
"""Write quickshell-tmux.conf with correct Unicode separator characters.

Called by quickshell Config.qml during tmux sync.
Accepts a JSON string as argv[1] with tmux settings.
"""
import sys, json, shutil, os

args = json.loads(sys.argv[1])
conf_path = os.path.expanduser("~/.config/tmux/quickshell-tmux.conf")

with open(conf_path, 'w') as f:
    f.write("# Auto-generated by quickshell — do not edit manually\n\n")

    # Status bar position
    position = "bottom" if args.get("statusBottom") else "top"
    f.write(f"set -g status-position {position}\n\n")

    # Separator shape
    if args.get("pill"):
        left_sep = chr(0xE0B6)   #
        right_sep = chr(0xE0B4)  #
        f.write(f'set -g @catppuccin_window_left_separator "{left_sep}"\n')
        f.write(f'set -g @catppuccin_window_right_separator "{right_sep}\u00a0"\n')
        f.write(f'set -g @catppuccin_status_left_separator  " {left_sep}"\n')
        f.write(f'set -g @catppuccin_status_right_separator "{right_sep} "\n')
    else:
        block = "\u2588"
        f.write(f'set -g @catppuccin_window_left_separator "{block}"\n')
        f.write(f'set -g @catppuccin_window_right_separator "{block} "\n')
        f.write(f'set -g @catppuccin_status_left_separator  " {block}"\n')
        f.write(f'set -g @catppuccin_status_right_separator "{block} "\n')

    # Window options
    f.write('set -g @catppuccin_window_middle_separator " \u2588"\n')
    f.write('set -g @catppuccin_window_number_position "right"\n')
    f.write('set -g @catppuccin_window_default_fill "number"\n')
    f.write('set -g @catppuccin_window_default_text "#W"\n')
    f.write('set -g @catppuccin_window_current_fill "number"\n')
    f.write('set -g @catppuccin_window_current_text "#W#{?window_zoomed_flag,(),}"\n\n')

    # Status modules
    f.write('set -g @catppuccin_status_modules_left "session"\n')
    f.write(f'set -g @catppuccin_status_modules_right "{args["modules_right"]}"\n')
    f.write('set -g @catppuccin_status_right_separator_inverse "no"\n')
    f.write('set -g @catppuccin_status_fill "icon"\n')
    f.write('set -g @catppuccin_status_connect_separator "no"\n\n')

    # Module-specific options
    f.write('set -g @catppuccin_directory_text "#{b:pane_current_path}"\n')
    clock_fmt = args.get("clockFormat", "")
    if clock_fmt:
        f.write(f'set -g @catppuccin_date_time_text "{clock_fmt}"\n')

# Copy custom modules to catppuccin plugin directory
custom_dir = os.path.expanduser("~/.config/tmux/plugins/catppuccin-tmux/custom")
src_dir = os.path.expanduser("~/jimdots/tmux")
os.makedirs(custom_dir, exist_ok=True)

for module in ['cpu', 'gpu', 'temp']:
    src = os.path.join(src_dir, f'{module}.sh')
    dst = os.path.join(custom_dir, f'{module}.sh')
    if os.path.exists(src):
        shutil.copy2(src, dst)
