# uosc — controls bar shown on hover near the bottom
controls=menu,gap,subtitles,<has_many_audio>audio,<has_many_video>video,<has_many_edition>editions,<stream>stream-quality,gap,space,speed,space,shuffle,loop-playlist,loop-file,gap,prev,items,next,gap,fullscreen
timeline_style=line
timeline_size=40
top_bar=no-border
top_bar_title=yes
top_bar_alt_title=${media-title}
progress=windowed
click_threshold=200
click_command=cycle pause; script-binding uosc/flash-pause-indicator
